"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mbot_status_t(object):
    __slots__ = ["utime", "status"]

    __typenames__ = ["int64_t", "int8_t"]

    __dimensions__ = [None, None]

    STATUS_IN_PROGRESS = 0
    STATUS_COMPLETE = 1
    STATUS_GOAL_INVALID = 2
    STATUS_NO_VALID_PATH = 3

    def __init__(self):
        self.utime = 0
        self.status = 0

    def encode(self):
        buf = BytesIO()
        buf.write(mbot_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.status))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mbot_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mbot_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mbot_status_t()
        self.utime, self.status = struct.unpack(">qb", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mbot_status_t in parents: return 0
        tmphash = (0x28edc52678586b83) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mbot_status_t._packed_fingerprint is None:
            mbot_status_t._packed_fingerprint = struct.pack(">Q", mbot_status_t._get_hash_recursive([]))
        return mbot_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

