"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import lcmtypes.pose_xyt_t

class mbot_command_t(object):
    __slots__ = ["utime", "state", "goal_pose", "num_obstacles", "obstacle_poses"]

    __typenames__ = ["int64_t", "int8_t", "lcmtypes.pose_xyt_t", "int32_t", "lcmtypes.pose_xyt_t"]

    __dimensions__ = [None, None, None, None, ["num_obstacles"]]

    STATE_STOPPED = 0
    STATE_MOVING = 1

    def __init__(self):
        self.utime = 0
        self.state = 0
        self.goal_pose = lcmtypes.pose_xyt_t()
        self.num_obstacles = 0
        self.obstacle_poses = []

    def encode(self):
        buf = BytesIO()
        buf.write(mbot_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.state))
        assert self.goal_pose._get_packed_fingerprint() == lcmtypes.pose_xyt_t._get_packed_fingerprint()
        self.goal_pose._encode_one(buf)
        buf.write(struct.pack(">i", self.num_obstacles))
        for i0 in range(self.num_obstacles):
            assert self.obstacle_poses[i0]._get_packed_fingerprint() == lcmtypes.pose_xyt_t._get_packed_fingerprint()
            self.obstacle_poses[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mbot_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mbot_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mbot_command_t()
        self.utime, self.state = struct.unpack(">qb", buf.read(9))
        self.goal_pose = lcmtypes.pose_xyt_t._decode_one(buf)
        self.num_obstacles = struct.unpack(">i", buf.read(4))[0]
        self.obstacle_poses = []
        for i0 in range(self.num_obstacles):
            self.obstacle_poses.append(lcmtypes.pose_xyt_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mbot_command_t in parents: return 0
        newparents = parents + [mbot_command_t]
        tmphash = (0xe884f1c967e65792+ lcmtypes.pose_xyt_t._get_hash_recursive(newparents)+ lcmtypes.pose_xyt_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mbot_command_t._packed_fingerprint is None:
            mbot_command_t._packed_fingerprint = struct.pack(">Q", mbot_command_t._get_hash_recursive([]))
        return mbot_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

